#!/usr/bin/env bash
# Clears ONLY this POC's demo-generated data. Safe to re-run.
#
# Scope (deliberately limited — see guide section 60):
#   - Truncates DEMO-database (aidp) rows: transactions, fraud_scores,
#     fraud_decisions, recent_events, customer_profiles, customers,
#     pipeline_runs. Table schema is NOT dropped.
#   - Clears local data/seed/ and data/output/ files (regenerated by
#     scripts/seed_data.sh + the batch pipeline).
#   - Clears objects in the aidp-raw/aidp-clean/aidp-curated/aidp-features
#     MinIO buckets.
#
# Deliberately NOT touched:
#   - aidp_test (the isolated integration-test database, fix H4)
#   - Docker containers/volumes/images, Redpanda topics
#   - MLflow's model registry / aidp-model-output bucket (the trained
#     model is left intact — run scripts/train_model.sh yourself if you
#     also want a freshly trained model)
#   - Anything outside this project directory
set -euo pipefail
cd "$(dirname "$0")/.."

if [ -d .venv ]; then
  source .venv/bin/activate
fi

if [ -f .env ]; then
  set -a; source .env; set +a
fi

echo "Resetting demo data (aidp database rows, data/seed, data/output, data-lake MinIO objects)..."

docker compose exec -T postgres psql -U "${POSTGRES_USER:-aidp}" -d "${POSTGRES_DB:-aidp}" -c "
TRUNCATE fraud_decisions, fraud_scores, transactions, recent_events, customer_profiles, customers, pipeline_runs RESTART IDENTITY CASCADE;
"

rm -rf data/seed/*.parquet data/seed/*.csv
rm -rf data/output/raw data/output/clean data/output/curated data/output/features data/output/rejected

python3 - <<'PYEOF'
from src.common.storage import get_minio_client

client = get_minio_client()
for bucket in ["aidp-raw", "aidp-clean", "aidp-curated", "aidp-features"]:
    for obj in client.list_objects(bucket, recursive=True):
        client.remove_object(bucket, obj.object_name)
print("Cleared data-lake bucket objects.")
PYEOF

echo "Demo data reset complete. Run ./scripts/seed_data.sh to regenerate."
